apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: instascale
  name: instascale
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: instascale
  template:
    metadata:
      labels:
        app: instascale
    spec:
      containers:
      - image: asm582/instascale:latest
        name: instascale
        resources:
          limits:
            cpu: "2"
            memory: "2G"
          requests:
            cpu: "2"
            memory: "2G"
      serviceAccountName: instascale-sa
